### ISSUE TITLE
Are you calculating Y_hat or X_hat?

### ISSUE THREAD

**Issue by lupupu** [PrinceJavier/causal_ccm#1]
https://github.com/PrinceJavier/causal_ccm/blob/d9c8be22f754258340d5177809e3fa938ed70020/causal_ccm/causal_ccm.py#L103

**Comment by lupupu** [comment]
The return is X_hat, and it is alway about X in the function of "predict".

**Comment by PrinceJavier** [comment]
Hi thanks for raising this. That should be X_hat. I've fixed the errors in the docstrings where X and Y were switched. Are they clearer now?

**Comment by lupupu** [comment]
> Hi thanks for raising this. That should be X_hat. I've fixed the errors in the docstrings where X and Y were switched. Are they clearer now?

Thank you. It is clear now. It would be better if you could update the python package.

**Comment by PrinceJavier** [comment]
Hi I've updated the package. Closing this issue
