### ISSUE TITLE
E and L parameter optimization

### ISSUE THREAD

**Issue by nsankar** [PrinceJavier/causal_ccm#3]
Thanks for developing this great library for CCM. My question is If we want to optimize the lag and embedding (tau and E) parameter values through some external statistical or ML method. in order to improve the causal correlations , In such a method should I consider the source timeseries X **or**  the target  time series Y as a reference series for the optimization of tau and E values?

**Comment by PrinceJavier** [comment]
I am not sure. Let's say we do not have an intuition of the direction of causation, might it make sense to try both ways and see how the optimal tau and E differ? I am not sure about this but might it be possible that the optimal parameters for X->Y are different from Y->X?
